name: kit3d-dev

services:
  kit3d-front:
    image: ${REGISTRY}/kit3d-front:${FRONT_TAG}
    #restart: unless-stopped
    platform: ${PLATFORM}
    depends_on:
      - kit3d-back
    networks:
      - kit3d
    labels:
      - "com.centurylinklabs.watchtower.scope=kit3d-dev"

  kit3d-back:
    image: ${REGISTRY}/kit3d-back:${BACK_TAG}
    platform: ${PLATFORM}
    #restart: unless-stopped
    environment:
      BACK_WORKERS: ${BACK_WORKERS}
      DB_HOST: kit3d-postgres
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      CELERY_BROKER_URL: amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@kit3d-rabbitmq:5672//
      CELERY_RESULT_BACKEND: redis://kit3d-redis:6379/0
      TERRAIN_CELERY_BROKER_URL: redis://kit3d-redis:6379/1
      TERRAIN_CELERY_RESULT_BACKEND: redis://kit3d-redis:6379/2
      DEFAULT_QUEUE: import_jobs
      CELERY_IMPORT_QUEUE: import_jobs
      CELERY_TILES_QUEUE: tile_jobs
      CELERY_TERRAIN_QUEUE: terrain_jobs
      ASSETS_DIR: /data/assets
    volumes:
      - ./data/assets:/data/assets
    depends_on:
      - kit3d-postgres
      - kit3d-rabbitmq
      - kit3d-redis
    networks:
      - kit3d
    labels:
      - "com.centurylinklabs.watchtower.scope=kit3d-dev"

  kit3d-engin-import:
    image: ${REGISTRY}/kit3d-engin:${ENGIN_TAG}
    platform: ${PLATFORM}
    #restart: unless-stopped
    environment:
      DB_HOST: kit3d-postgres
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      PGPASSWORD: ${POSTGRES_PASSWORD}
      CELERY_BROKER_URL: amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@kit3d-rabbitmq:5672//
      CELERY_RESULT_BACKEND: redis://kit3d-redis:6379/0
      DEFAULT_QUEUE: import_jobs
      CELERY_QUEUE: import_jobs
      CELERY_PREFETCH: "1"
      CELERY_BROKER_HEARTBEAT: "0"
      #CELERY_CONCURRENCY: "10"
      CELERY_AUTOSCALE: "10,4"
      ASSETS_DIR: /data/assets
      PG2B3DM_BIN: /usr/local/bin/pg2b3dm
      GLTF_PIPELINE_BIN: /usr/local/bin/gltf-pipeline
    volumes:
      - ./data/assets:/data/assets
    depends_on:
      - kit3d-postgres
      - kit3d-rabbitmq
      - kit3d-redis
    networks:
      - kit3d
    #labels:
    #  - "com.centurylinklabs.watchtower.scope=kit3d-dev"

  kit3d-engin-tile:
    image: ${REGISTRY}/kit3d-engin:${ENGIN_TAG}
    platform: ${PLATFORM}
    #restart: unless-stopped
    environment:
      DB_HOST: kit3d-postgres
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      PGPASSWORD: ${POSTGRES_PASSWORD}
      CELERY_BROKER_URL: amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@kit3d-rabbitmq:5672//
      CELERY_RESULT_BACKEND: redis://kit3d-redis:6379/0
      DEFAULT_QUEUE: import_jobs
      CELERY_QUEUE: tile_jobs
      CELERY_PREFETCH: "1"
      CELERY_BROKER_HEARTBEAT: "0"
      #CELERY_CONCURRENCY: "4"
      CELERY_AUTOSCALE: "10,4"
      ASSETS_DIR: /data/assets
      PG2B3DM_BIN: /usr/local/bin/pg2b3dm
      GLTF_PIPELINE_BIN: /usr/local/bin/gltf-pipeline
    volumes:
      - ./data/assets:/data/assets
    depends_on:
      - kit3d-postgres
      - kit3d-rabbitmq
      - kit3d-redis
    networks:
      - kit3d
    #labels:
    #  - "com.centurylinklabs.watchtower.scope=kit3d-dev"

  kit3d-flower:
    build: kit3d-flower
    platform: ${PLATFORM}
    #restart: unless-stopped
    environment:
      CELERY_BROKER_URL: amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@kit3d-rabbitmq:5672//
      CELERY_RESULT_BACKEND: redis://kit3d-redis:6379/0
      FLOWER_BASIC_AUTH: ${FLOWER_BASIC_AUTH}
    ports:
      - "5556:5555"
    volumes:
      - kit3d_flower_data:/data
    depends_on:
      - kit3d-rabbitmq
      - kit3d-redis
    networks:
      - kit3d

  kit3d-postgres:
    image: postgis/postgis:18-3.6
    platform: ${PLATFORM}
    #restart: unless-stopped
    environment:
      TZ: Asia/Seoul
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./data/postgres:/var/lib/postgresql
    ports:
      - "5433:5432"
    networks:
      - kit3d

  kit3d-pgadmin:
    image: dpage/pgadmin4:8
    platform: ${PLATFORM}
    #restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "5052:80"
    volumes:
      - kit3d_pgadmin_data:/var/lib/pgadmin
    depends_on:
      - kit3d-postgres
    networks:
      - kit3d

  kit3d-rabbitmq:
    image: rabbitmq:3-management
    platform: ${PLATFORM}
    #restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    volumes:
      - kit3d_rabbitmq_data:/var/lib/rabbitmq
      - ./kit3d-rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
    ports:
      - "15673:15672"
    networks:
      - kit3d

  kit3d-redis:
    image: redis:7-alpine
    platform: ${PLATFORM}
    #restart: unless-stopped
    volumes:
      - kit3d_redis_data:/data
    networks:
      - kit3d

  kit3d-proxy:
    image: nginx:1.27-alpine
    platform: ${PLATFORM}
    #restart: unless-stopped
    ports:
      - "81:80"
    volumes:
      - ./kit3d-proxy/conf.d:/etc/nginx/conf.d:ro
      - ./data/assets:/data/assets:ro
    depends_on:
      - kit3d-front
      - kit3d-back
    networks:
      - kit3d

  kit3d-flyway:
    image: flyway/flyway:latest
    platform: ${PLATFORM}
    environment:
      FLYWAY_URL: jdbc:postgresql://kit3d-postgres:5432/${POSTGRES_DB}
      FLYWAY_USER: ${POSTGRES_USER}
      FLYWAY_PASSWORD: ${POSTGRES_PASSWORD}
      FLYWAY_CONNECT_RETRIES: 10
    command: migrate
    volumes:
      - ./migrations:/flyway/sql:ro
    depends_on:
      - kit3d-postgres
    networks:
      - kit3d

  kit3d-watchtower:
    image: containrrr/watchtower:latest
    platform: ${PLATFORM}
    #restart: unless-stopped
    environment:
      - TZ=Asia/Seoul
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 60 --cleanup --scope kit3d-dev
    labels: ["com.centurylinklabs.watchtower.scope=kit3d-dev"]

networks:
  kit3d:

volumes:
  kit3d_pgadmin_data:
  kit3d_rabbitmq_data:
  kit3d_redis_data:
  kit3d_flower_data:
