name: kit3d-dev

services:
  kit3d-front:
    image: ${REGISTRY}/kit3d-front:${FRONT_TAG}
    restart: unless-stopped
    platform: ${PLATFORM}
    depends_on:
      - kit3d-back
    networks:
      - kit3d
    labels:
      - "com.centurylinklabs.watchtower.scope=kit3d-dev"

  kit3d-back:
    image: ${REGISTRY}/kit3d-back:${BACK_TAG}
    platform: ${PLATFORM}
    restart: unless-stopped
    environment:
      DB_HOST: kit3d-postgres
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      CELERY_BROKER_URL: amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@kit3d-rabbitmq:5672//
      CELERY_QUEUE: import_jobs
      CELERY_TILES_QUEUE: tile_jobs
      UPLOAD_DIR: /data/assets
    volumes:
      - ./data/assets:/data/assets
    depends_on:
      - kit3d-postgres
      - kit3d-rabbitmq
    networks:
      - kit3d
    labels:
      - "com.centurylinklabs.watchtower.scope=kit3d-dev"

  kit3d-engin:
    image: ${REGISTRY}/kit3d-engin:${ENGIN_TAG}
    platform: ${PLATFORM}
    restart: unless-stopped
    environment:
      DB_HOST: kit3d-postgres
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      PGPASSWORD: ${POSTGRES_PASSWORD}
      CELERY_BROKER_URL: amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@kit3d-rabbitmq:5672//
      CELERY_QUEUE: import_jobs
      CELERY_PREFETCH: "1"
      CELERY_BROKER_HEARTBEAT: "0"
      ASSETS_DIR: /data/assets
      PG2B3DM_BIN: /usr/local/bin/pg2b3dm
      GLTF_PIPELINE_BIN: /usr/local/bin/gltf-pipeline
      CELERY_QUEUES: import_jobs,tile_jobs
      CELERY_CONCURRENCY: "4"
    volumes:
      - ./data/assets:/data/assets
    depends_on:
      - kit3d-postgres
      - kit3d-rabbitmq
    networks:
      - kit3d
    #labels:
    #  - "com.centurylinklabs.watchtower.scope=kit3d"

  kit3d-postgres:
    image: postgis/postgis:18-3.6
    platform: ${PLATFORM}
    restart: unless-stopped
    environment:
      TZ: Asia/Seoul
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./data/postgres:/var/lib/postgresql
    ports:
      - "5432:5432"
    networks:
      - kit3d

  kit3d-pgadmin:
    image: dpage/pgadmin4:8
    platform: ${PLATFORM}
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:80"
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin
    depends_on:
      - kit3d-postgres
    networks:
      - kit3d

  kit3d-rabbitmq:
    image: rabbitmq:3-management
    platform: ${PLATFORM}
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq
    ports:
      - "15672:15672"
    networks:
      - kit3d

  kit3d-proxy:
    image: nginx:1.27-alpine
    platform: ${PLATFORM}
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.scope=kit3d-dev"
    ports:
      - "80:80"
    volumes:
      - ./kit3d-proxy/conf.d:/etc/nginx/conf.d:ro
      - ./data/assets:/data/assets:ro
    depends_on:
      - kit3d-front
      - kit3d-back
    networks:
      - kit3d

  kit3d-flyway:
    image: flyway/flyway:latest
    platform: ${PLATFORM}
    command: >
      -url=jdbc:postgresql://kit3d-postgres:5432/${POSTGRES_DB}
      -user=${POSTGRES_USER}
      -password=${POSTGRES_PASSWORD}
      -connectRetries=10
      migrate
    volumes:
      - ./migrations:/flyway/sql:ro
    depends_on:
      - kit3d-postgres
    networks:
      - kit3d

  kit3d-watchtower:
    image: containrrr/watchtower:latest
    platform: ${PLATFORM}
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 60 --cleanup --scope kit3d-dev
    labels: ["com.centurylinklabs.watchtower.scope=kit3d-dev"]
    

networks:
  kit3d:
