map $uri $cc_header {
  default "";
  ~*\.json$ "public, max-age=300";
  ~*\.(glb|b3dm|i3dm|cmpt)$ "public, max-age=2592000";
}
 
server {
  listen 80;
  listen [::]:80;
  server_name localhost;

  client_max_body_size 2g;

  gzip on;
	gzip_types *;
	gzip_comp_level 9;
	gzip_proxied any;
	gzip_vary on;

  # 외부 접근은 프론트엔드로
  location / {
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

    proxy_pass http://kit3d-front:80;
  }

  #  API 요청은 백엔드로 프록시
  location /api/ {
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

    proxy_pass http://kit3d-back:8080;
  }

  # ifc files 미리보기 전달
  location /assets/ {
    alias /data/assets/;
    try_files $uri =404;

    add_header Cache-Control $cc_header always;
    add_header Access-Control-Allow-Origin "*" always;
    add_header Access-Control-Allow-Methods "GET, HEAD, OPTIONS" always;
    add_header Access-Control-Allow-Headers "Origin, Range, Accept, Content-Type, Authorization" always;
    add_header Access-Control-Expose-Headers "Content-Length, Content-Range" always;
  }

  # 3d tiles 전달
  location /tiles/ {
    alias /data/assets/;
    try_files $uri =404;

    types {
      application/json json;
      application/octet-stream b3dm i3dm cmpt glb;
    }
    default_type application/octet-stream;

    add_header Cache-Control $cc_header always;
    add_header Access-Control-Allow-Origin "*" always;
    add_header Access-Control-Allow-Methods "GET, HEAD, OPTIONS" always;
    add_header Access-Control-Allow-Headers "Origin, Range, Accept, Content-Type, Authorization" always;
    add_header Access-Control-Expose-Headers "Content-Length, Content-Range" always;
  }
  
  # terrain 파일 전달
  location ~ ^/dem/(.*\.terrain)$ {
    # alias C:/;
    # gzip off;
    # default_type application/octet-stream;
    # add_header Content-Encoding gzip;
    # add_header Access-Control-Allow-Origin *;
  }
}
